-- ---------------------------------------------------------------
-- Hearth — content bank (spec §17)
--
-- GENERATED FILE. Do not edit by hand: change content/*.json and run
--   npm run seed:sql
--
-- 222 Fake Artist words, 101 Dial spectrum pairs,
-- 34 Season rules, 42 Envelope assignments.
-- Safe to re-run: existing rows are matched on their payload.
-- ---------------------------------------------------------------

insert into content_items (game_type, payload, category, difficulty)
select v.game_type, v.payload, v.category, v.difficulty
from (values
  ('fake_artist', '{"text":"Piano","description":"A large instrument with black and white keys","aliases":["piano","grand piano","upright piano","keyboard"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Frying pan","description":"A flat kitchen pan with a long handle","aliases":["frying pan","fry pan","skillet","pan"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Umbrella","description":"Canopy on a stick that keeps the rain off you","aliases":["umbrella","brolly","parasol"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Lighthouse","description":"Tall tower on the coast with a lamp at the top","aliases":["lighthouse","light house"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Octopus","description":"Sea creature with eight arms","aliases":["octopus","squid"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Bicycle","description":"Two wheels, a frame and pedals","aliases":["bicycle","bike","push bike","cycle"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Windmill","description":"Tower with sails that turn in the wind","aliases":["windmill","wind mill","wind turbine"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Toothbrush","description":"Small brush on a handle for your teeth","aliases":["toothbrush","tooth brush"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Hot air balloon","description":"Huge balloon with a basket hanging beneath","aliases":["hot air balloon","balloon","air balloon"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Cactus","description":"Spiky desert plant with thick arms","aliases":["cactus","succulent","saguaro"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Hammer","description":"Tool with a heavy head for driving nails","aliases":["hammer","mallet"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Jellyfish","description":"Floating sea creature with trailing tentacles","aliases":["jellyfish","jelly fish"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Traffic light","description":"Pole with red, amber and green lamps","aliases":["traffic light","stoplight","traffic signal","stop light"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Wheelbarrow","description":"One wheel, two handles, a tray for carrying soil","aliases":["wheelbarrow","wheel barrow","barrow"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Pineapple","description":"Spiky tropical fruit with a leafy crown","aliases":["pineapple","pine apple"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Telescope","description":"Long tube on a tripod for looking at stars","aliases":["telescope"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Kettle","description":"Pot with a spout for boiling water","aliases":["kettle","tea kettle"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Snail","description":"Slow creature carrying a spiral shell","aliases":["snail"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Ladder","description":"Two rails joined by rungs for climbing","aliases":["ladder","step ladder"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Sunflower","description":"Tall flower with a dark centre and yellow petals","aliases":["sunflower","sun flower"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Anchor","description":"Heavy hook that holds a boat in place","aliases":["anchor"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Guitar","description":"Stringed instrument with a waisted body","aliases":["guitar","acoustic guitar","electric guitar"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Igloo","description":"Dome shelter built from blocks of snow","aliases":["igloo"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Peacock","description":"Bird with an enormous fan of patterned feathers","aliases":["peacock","peafowl"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Chessboard","description":"Grid of alternating light and dark squares","aliases":["chessboard","chess board","checkerboard","chess set"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Volcano","description":"Mountain with smoke and lava at the summit","aliases":["volcano"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Shopping trolley","description":"Wire basket on wheels you push around a supermarket","aliases":["shopping trolley","shopping cart","trolley","cart"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Owl","description":"Round night bird with enormous forward eyes","aliases":["owl"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Sandcastle","description":"Turrets built from wet sand at the beach","aliases":["sandcastle","sand castle"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Microphone","description":"Mesh ball on a stick you sing into","aliases":["microphone","mic","mike"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Waterfall","description":"River falling over a cliff edge","aliases":["waterfall","water fall","falls"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Spider web","description":"Radiating threads spun between two branches","aliases":["spider web","cobweb","web","spiderweb"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Hedgehog","description":"Small round animal covered in spines","aliases":["hedgehog"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Suitcase","description":"Rectangular case with a handle for travelling","aliases":["suitcase","luggage","travel case","briefcase"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Sewing machine","description":"Table machine with a needle arm and a foot plate","aliases":["sewing machine"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Pretzel","description":"Knotted baked bread with salt on top","aliases":["pretzel"]}'::jsonb, 'food', 2),
  ('fake_artist', '{"text":"Trumpet","description":"Brass horn with three valves and a wide bell","aliases":["trumpet","cornet","brass horn","horn"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Crab","description":"Flat shelled creature with two big claws","aliases":["crab"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Chandelier","description":"Hanging light with tiers of glass drops","aliases":["chandelier"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Tent","description":"Fabric triangle pegged to the ground for sleeping in","aliases":["tent","camping tent"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Wristwatch","description":"Small clock face on a strap","aliases":["wristwatch","watch","wrist watch"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Corkscrew","description":"Spiral tool for pulling corks out of bottles","aliases":["corkscrew","cork screw","bottle opener"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Giraffe","description":"Tall spotted animal with a very long neck","aliases":["giraffe"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Bridge","description":"Span carrying a road over water","aliases":["bridge"]}'::jsonb, 'places', 1),
  ('fake_artist', '{"text":"Fire hydrant","description":"Squat street post with side nozzles for hoses","aliases":["fire hydrant","hydrant","fireplug"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Watering can","description":"Container with a handle and a long spout","aliases":["watering can","water can"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Penguin","description":"Upright black and white bird that cannot fly","aliases":["penguin"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Cuckoo clock","description":"Wooden house clock with a bird and hanging weights","aliases":["cuckoo clock"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Skateboard","description":"Wooden deck on four small wheels","aliases":["skateboard","skate board"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Cupcake","description":"Small cake in a paper case with a swirl of icing","aliases":["cupcake","cup cake","fairy cake","muffin"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Harp","description":"Tall triangular frame strung with many strings","aliases":["harp"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Mushroom","description":"Domed cap on a short pale stalk","aliases":["mushroom","toadstool","fungus"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Padlock","description":"Metal body with a curved shackle and a keyhole","aliases":["padlock","lock"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Dolphin","description":"Smooth grey sea mammal with a curved fin","aliases":["dolphin","porpoise"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Fountain","description":"Stone basin with water arcing from the middle","aliases":["fountain","water fountain"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Boomerang","description":"Bent flat stick that returns when thrown","aliases":["boomerang"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Camera","description":"Box with a lens and a shutter button","aliases":["camera"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Beehive","description":"Stack of boxes or a dome where bees live","aliases":["beehive","bee hive","hive"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Toaster","description":"Metal box with two slots and a lever","aliases":["toaster"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Kangaroo","description":"Hopping animal with a heavy tail and a pouch","aliases":["kangaroo","wallaby"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Scarecrow","description":"Straw figure on a cross of poles in a field","aliases":["scarecrow","scare crow"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Saxophone","description":"Curved brass instrument with keys and an upturned bell","aliases":["saxophone","sax"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Ice cream cone","description":"Scoops of ice cream in a pointed wafer","aliases":["ice cream cone","ice cream","cone","gelato"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Compass","description":"Round case with a needle pointing north","aliases":["compass"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Zebra","description":"Horse covered in black and white stripes","aliases":["zebra"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Treehouse","description":"Wooden hut built up in the branches","aliases":["treehouse","tree house"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Vacuum cleaner","description":"Wheeled canister with a hose and a floor head","aliases":["vacuum cleaner","vacuum","hoover"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Lobster","description":"Long shelled sea creature with big front claws","aliases":["lobster","crayfish"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Rocking chair","description":"Wooden chair on two curved runners","aliases":["rocking chair","rocker"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Cathedral","description":"Huge church with spires and arched windows","aliases":["cathedral","church","chapel","abbey"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Paint roller","description":"Cylinder on a bent handle for painting walls","aliases":["paint roller","roller"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Rhinoceros","description":"Heavy grey animal with a horn on its nose","aliases":["rhinoceros","rhino"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Birthday cake","description":"Tiered cake with lit candles on top","aliases":["birthday cake","cake"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Stethoscope","description":"Tubes from two earpieces down to a round disc","aliases":["stethoscope"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Seahorse","description":"Small upright fish with a curled tail","aliases":["seahorse","sea horse"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Roller coaster","description":"Track with steep hills and a train of carts","aliases":["roller coaster","rollercoaster"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Mailbox","description":"Box on a post with a flag for letters","aliases":["mailbox","post box","letterbox","mail box","postbox"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Pinecone","description":"Scaly oval seed pod from a fir tree","aliases":["pinecone","pine cone"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Accordion","description":"Folding bellows box with buttons on both ends","aliases":["accordion","concertina","squeezebox"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Bat","description":"Small flying mammal with leathery wings","aliases":["bat","fruit bat"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Greenhouse","description":"Glass building full of plants","aliases":["greenhouse","green house","glasshouse"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Sundial","description":"Flat dial with an angled blade that casts a shadow","aliases":["sundial","sun dial"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Flamingo","description":"Pink bird standing on one thin leg","aliases":["flamingo"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Waffle","description":"Square griddled batter with a grid of deep pockets","aliases":["waffle","waffles"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Trombone","description":"Brass instrument with a long sliding tube","aliases":["trombone"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Bonfire","description":"Stacked logs with flames rising off them","aliases":["bonfire","campfire","fire","camp fire"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Wheel of cheese","description":"Thick round cheese with a wedge cut out","aliases":["wheel of cheese","cheese","cheese wheel"]}'::jsonb, 'food', 2),
  ('fake_artist', '{"text":"Submarine","description":"Sealed underwater vessel with a conning tower","aliases":["submarine","sub","u boat"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Chameleon","description":"Lizard with a curled tail and swivelling eyes","aliases":["chameleon","lizard"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Barn","description":"Large farm building with big double doors","aliases":["barn","farmhouse","farm"]}'::jsonb, 'places', 1),
  ('fake_artist', '{"text":"Feather","description":"Light quill with a soft vane on each side","aliases":["feather","quill","plume"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Espresso machine","description":"Cafe machine with a group head and a steam wand","aliases":["espresso machine","coffee machine","coffee maker"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Beetle","description":"Insect with a hard split shell over its back","aliases":["beetle","bug","ladybird","ladybug"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Staircase","description":"Flight of steps with a handrail","aliases":["staircase","stairs","stairway","steps"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Kite","description":"Diamond of fabric on a string with a tail","aliases":["kite"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Pelican","description":"Big water bird with a pouch under its beak","aliases":["pelican"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Doughnut","description":"Ring of fried dough with icing and sprinkles","aliases":["doughnut","donut"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Metronome","description":"Pyramid box with a swinging weighted arm","aliases":["metronome"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Iceberg","description":"Floating mountain of ice, mostly underwater","aliases":["iceberg","ice berg"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Drum kit","description":"Several drums and cymbals arranged around a stool","aliases":["drum kit","drums","drum set","drumkit"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Tortoise","description":"Slow reptile with a domed shell and stumpy legs","aliases":["tortoise","turtle"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Ferris wheel","description":"Giant upright wheel hung with passenger cabins","aliases":["ferris wheel","big wheel","observation wheel"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Screwdriver","description":"Handle with a shaft and a flat or cross tip","aliases":["screwdriver","screw driver"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Swan","description":"White water bird with a long curved neck","aliases":["swan","goose"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Pizza slice","description":"Triangle of pizza with toppings and stretched cheese","aliases":["pizza slice","pizza","slice of pizza"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Wind chime","description":"Hanging tubes that clink together in the breeze","aliases":["wind chime","windchime","chimes"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Canyon","description":"Deep gorge with layered rock walls and a river below","aliases":["canyon","gorge","ravine"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Typewriter","description":"Machine with round keys and a paper roller","aliases":["typewriter","type writer"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Moose","description":"Large deer with wide flat antlers","aliases":["moose","elk"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Castle","description":"Stone fort with towers and battlements","aliases":["castle","fortress","fort","keep"]}'::jsonb, 'places', 1),
  ('fake_artist', '{"text":"Whisk","description":"Handle with looping wires for beating eggs","aliases":["whisk","egg beater"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Starfish","description":"Five-armed creature from a rock pool","aliases":["starfish","sea star","star fish"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Popcorn","description":"Striped tub overflowing with puffed kernels","aliases":["popcorn","pop corn"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Xylophone","description":"Row of graded bars struck with two beaters","aliases":["xylophone","glockenspiel"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Tornado","description":"Twisting funnel of cloud touching the ground","aliases":["tornado","twister","cyclone","whirlwind"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Bunk bed","description":"Two beds stacked with a ladder between them","aliases":["bunk bed","bunk beds","bunks"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Porcupine","description":"Animal bristling with long sharp quills","aliases":["porcupine"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Aquarium","description":"Glass tank with fish, gravel and weed","aliases":["aquarium","fish tank","tank"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Wheelchair","description":"Chair with two large side wheels and small casters","aliases":["wheelchair","wheel chair"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Walrus","description":"Blubbery sea mammal with two long tusks","aliases":["walrus"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Lemon","description":"Oval yellow citrus fruit","aliases":["lemon","citrus"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Binoculars","description":"Two joined tubes you look through with both eyes","aliases":["binoculars","field glasses"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Coral reef","description":"Branching underwater structure full of fish","aliases":["coral reef","coral","reef"]}'::jsonb, 'nature', 3),
  ('fake_artist', '{"text":"Postage stamp","description":"Small perforated square stuck to an envelope","aliases":["postage stamp","stamp"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Ostrich","description":"Huge flightless bird with a long bare neck","aliases":["ostrich","emu"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Diving board","description":"Springboard jutting out over a swimming pool","aliases":["diving board","springboard","high dive"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Nutcracker","description":"Two hinged arms squeezed together to crack shells","aliases":["nutcracker","nut cracker"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Firefly","description":"Small beetle with a glowing tail","aliases":["firefly","fire fly","glow worm","lightning bug"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Croissant","description":"Flaky crescent-shaped pastry","aliases":["croissant"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Weathervane","description":"Rooftop arrow with a cockerel that turns in the wind","aliases":["weathervane","weather vane","wind vane"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Glacier","description":"Slow river of ice grinding down a valley","aliases":["glacier"]}'::jsonb, 'nature', 3),
  ('fake_artist', '{"text":"Trampoline","description":"Round sprung mat on legs with a safety net","aliases":["trampoline"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Armadillo","description":"Animal armoured with hard banded plates","aliases":["armadillo","pangolin"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Pier","description":"Wooden walkway on stilts running out to sea","aliases":["pier","jetty","boardwalk","dock"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Magnifying glass","description":"Round lens in a rim with a handle","aliases":["magnifying glass","magnifier","loupe"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Praying mantis","description":"Green insect with folded front legs","aliases":["praying mantis","mantis"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Sushi roll","description":"Rice and filling wrapped in seaweed, cut into rounds","aliases":["sushi roll","sushi","maki"]}'::jsonb, 'food', 2),
  ('fake_artist', '{"text":"Stalactite","description":"Stone spike hanging from a cave ceiling","aliases":["stalactite","stalagmite"]}'::jsonb, 'nature', 3),
  ('fake_artist', '{"text":"Fire escape","description":"Iron stairs zigzagging down a building''s outside wall","aliases":["fire escape"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Hourglass","description":"Two glass bulbs with sand running between them","aliases":["hourglass","hour glass","egg timer","sand timer"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Woodpecker","description":"Bird clinging to a trunk with a chisel beak","aliases":["woodpecker","wood pecker"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Watermelon","description":"Striped green melon with red flesh and black seeds","aliases":["watermelon","water melon","melon"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Periscope","description":"Bent tube with mirrors for seeing over things","aliases":["periscope"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Dandelion","description":"Seed head of fine white parachutes on a stem","aliases":["dandelion","dandelion clock"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Carousel","description":"Fairground ride of painted horses on poles","aliases":["carousel","merry go round","roundabout","merrygoround"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Bagpipes","description":"Bag under the arm with several pipes sticking out","aliases":["bagpipes","bag pipes","pipes"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Pufferfish","description":"Round spiky fish inflated like a ball","aliases":["pufferfish","puffer fish","blowfish"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Baguette","description":"Long thin loaf with slashes across the crust","aliases":["baguette","french bread","bread"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Rubber duck","description":"Yellow bath toy shaped like a duckling","aliases":["rubber duck","bath duck","duck"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Avalanche","description":"Wall of snow pouring down a mountainside","aliases":["avalanche","landslide"]}'::jsonb, 'nature', 3),
  ('fake_artist', '{"text":"Revolving door","description":"Four glass panels turning inside a drum","aliases":["revolving door","spinning door"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Dartboard","description":"Circular board of numbered wedges with a bullseye","aliases":["dartboard","dart board","darts"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Toucan","description":"Bird with an enormous bright curved beak","aliases":["toucan"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Cheeseburger","description":"Stacked bun, patty, cheese and salad","aliases":["cheeseburger","burger","hamburger"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Hairdryer","description":"Handheld nozzle that blows hot air","aliases":["hairdryer","hair dryer","blow dryer"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Whirlpool","description":"Spiralling funnel of water sucking downward","aliases":["whirlpool","vortex","maelstrom"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Escalator","description":"Moving staircase between two floors","aliases":["escalator","moving stairs"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Slingshot","description":"Y-shaped fork with an elastic band across it","aliases":["slingshot","catapult","sling shot"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Anteater","description":"Animal with a long tube snout and a bushy tail","aliases":["anteater","ant eater"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Pancake stack","description":"Pile of round pancakes with syrup running down","aliases":["pancake stack","pancakes","pancake","flapjacks"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Fishing rod","description":"Long flexible pole with a reel and a line","aliases":["fishing rod","fishing pole","rod"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Rainbow","description":"Arc of coloured bands across the sky","aliases":["rainbow"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Drawbridge","description":"Castle bridge on chains that lifts up","aliases":["drawbridge","draw bridge"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Lawnmower","description":"Wheeled cutter with a long push handle","aliases":["lawnmower","lawn mower","mower"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Chinchilla","description":"Very fluffy rodent with huge round ears","aliases":["chinchilla","hamster","gerbil"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Fortune cookie","description":"Folded wafer with a slip of paper poking out","aliases":["fortune cookie","cookie"]}'::jsonb, 'food', 2),
  ('fake_artist', '{"text":"Snow globe","description":"Glass dome on a base with a scene and falling flakes","aliases":["snow globe","snowglobe"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Geyser","description":"Jet of boiling water erupting from the ground","aliases":["geyser","hot spring"]}'::jsonb, 'nature', 3),
  ('fake_artist', '{"text":"Vending machine","description":"Glass-fronted cabinet with spirals holding snacks","aliases":["vending machine"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Coat hanger","description":"Triangular frame with a hook on top","aliases":["coat hanger","hanger","clothes hanger"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Meerkat","description":"Slim animal standing upright on its hind legs","aliases":["meerkat","mongoose"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Spaghetti","description":"Nest of long strands with a fork twirling them","aliases":["spaghetti","pasta","noodles"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Metal detector","description":"Long shaft with a flat disc held above the sand","aliases":["metal detector"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Eclipse","description":"Dark disc covering the sun with a bright ring around it","aliases":["eclipse","solar eclipse"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Phone box","description":"Upright glass booth with a telephone inside","aliases":["phone box","telephone box","phone booth","call box"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Jigsaw puzzle","description":"Interlocking pieces with one gap left","aliases":["jigsaw puzzle","jigsaw","puzzle"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Sloth","description":"Shaggy animal hanging upside down from a branch","aliases":["sloth"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Toothpaste tube","description":"Squeezed tube with a curl coming out of the cap","aliases":["toothpaste tube","toothpaste","tube of toothpaste"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Firework","description":"Burst of sparks spreading out across a night sky","aliases":["firework","fireworks","rocket"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Bowling pin","description":"Tall white skittle with two red bands","aliases":["bowling pin","skittle","pin","ten pin"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Otter","description":"Sleek river animal floating on its back","aliases":["otter"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Traffic cone","description":"Orange cone with a white reflective band","aliases":["traffic cone"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Observatory","description":"Domed building with a slot open to the sky","aliases":["observatory","planetarium"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Clothesline","description":"Rope of pegged washing strung between two posts","aliases":["clothesline","washing line","clothes line"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Narwhal","description":"Arctic whale with a single long spiral tusk","aliases":["narwhal","narwhale"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Wedding cake","description":"Tall tiered white cake with figures on top","aliases":["wedding cake","tiered cake"]}'::jsonb, 'food', 2),
  ('fake_artist', '{"text":"Stapler","description":"Hinged desk tool that clamps paper together","aliases":["stapler"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Quicksand","description":"Sinking patch of sand with a hand reaching out","aliases":["quicksand","quick sand"]}'::jsonb, 'nature', 3),
  ('fake_artist', '{"text":"Turnstile","description":"Waist-high barrier with rotating metal arms","aliases":["turnstile","barrier"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Yo-yo","description":"Two discs on an axle with a string looped round it","aliases":["yo yo","yoyo"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Platypus","description":"Furry swimmer with a duck''s bill and a flat tail","aliases":["platypus","duck billed platypus"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Candy cane","description":"Hooked stick striped red and white","aliases":["candy cane","candycane"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Bird cage","description":"Domed cage of bars with a swing and a hook","aliases":["bird cage","birdcage","cage"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Sand dune","description":"Rippled ridge of desert sand with a sharp crest","aliases":["sand dune","dune","dunes"]}'::jsonb, 'nature', 2),
  ('fake_artist', '{"text":"Bus stop","description":"Shelter with a bench and a timetable sign","aliases":["bus stop","bus shelter"]}'::jsonb, 'places', 1),
  ('fake_artist', '{"text":"Kaleidoscope","description":"Tube you look down at a symmetrical pattern","aliases":["kaleidoscope"]}'::jsonb, 'objects', 3),
  ('fake_artist', '{"text":"Pigeon","description":"Plump grey city bird strutting on a ledge","aliases":["pigeon","dove"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Sandwich","description":"Two slices of bread cut into a filled triangle","aliases":["sandwich","sarnie","butty"]}'::jsonb, 'food', 1),
  ('fake_artist', '{"text":"Grandfather clock","description":"Tall wooden case with a face and a swinging pendulum","aliases":["grandfather clock","longcase clock","pendulum clock"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Mirror","description":"Framed glass showing a reflection","aliases":["mirror","looking glass"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Seagull","description":"White coastal bird with grey wings, mid-squawk","aliases":["seagull","gull"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Ski lift","description":"Chairs hanging from a cable up a snowy slope","aliases":["ski lift","chairlift","chair lift","gondola"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Bandage","description":"Strip of gauze wound around a limb","aliases":["bandage","plaster","bandaid","band aid"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Hummingbird","description":"Tiny bird hovering at a flower with a needle beak","aliases":["hummingbird","humming bird"]}'::jsonb, 'animals', 3),
  ('fake_artist', '{"text":"Chopsticks","description":"Two tapered sticks held in one hand","aliases":["chopsticks","chop sticks"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Swing set","description":"Frame with a seat hanging on two chains","aliases":["swing set","swing","swings"]}'::jsonb, 'places', 1),
  ('fake_artist', '{"text":"Lantern","description":"Glass case around a flame with a carry handle","aliases":["lantern","lamp","oil lamp"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Squirrel","description":"Small climber with a big curled bushy tail","aliases":["squirrel","chipmunk"]}'::jsonb, 'animals', 1),
  ('fake_artist', '{"text":"Bell tower","description":"Stone tower with a large bell hanging in the arch","aliases":["bell tower","belfry","campanile"]}'::jsonb, 'places', 2),
  ('fake_artist', '{"text":"Paperclip","description":"Looped wire that holds sheets together","aliases":["paperclip","paper clip","clip"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Beaver","description":"Rodent with a flat paddle tail beside a dam","aliases":["beaver"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Ice rink","description":"Oval of ice with skate marks and a barrier around it","aliases":["ice rink","skating rink","rink"]}'::jsonb, 'places', 3),
  ('fake_artist', '{"text":"Balloon animal","description":"Twisted long balloon shaped like a dog","aliases":["balloon animal","balloon dog"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Cello","description":"Large stringed instrument played upright with a bow","aliases":["cello","double bass","violin"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Pyramid","description":"Huge stone triangle standing in the desert","aliases":["pyramid","pyramids"]}'::jsonb, 'places', 1),
  ('fake_artist', '{"text":"Hammock","description":"Sling of net or cloth slung between two trees","aliases":["hammock"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Raccoon","description":"Masked animal with a ringed bushy tail","aliases":["raccoon","racoon"]}'::jsonb, 'animals', 2),
  ('fake_artist', '{"text":"Teapot","description":"Round pot with a spout, a lid and a curled handle","aliases":["teapot","tea pot"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Bookshelf","description":"Shelves of books, some leaning over","aliases":["bookshelf","book shelf","bookcase"]}'::jsonb, 'objects', 1),
  ('fake_artist', '{"text":"Cliff","description":"Sheer rock face dropping to the sea","aliases":["cliff","cliffs","cliff face"]}'::jsonb, 'nature', 1),
  ('fake_artist', '{"text":"Tuxedo","description":"Dinner jacket with a bow tie and satin lapels","aliases":["tuxedo","tux","dinner jacket","suit"]}'::jsonb, 'objects', 2),
  ('fake_artist', '{"text":"Bulldozer","description":"Tracked machine with a wide push blade at the front","aliases":["bulldozer","digger","excavator"]}'::jsonb, 'objects', 2),
  ('dial', '{"left":"Cold","right":"Hot"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Underrated","right":"Overrated"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Quiet","right":"Loud"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Cheap","right":"Expensive"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Small","right":"Huge"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Boring","right":"Exciting"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Ugly","right":"Beautiful"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Useless","right":"Essential"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Soft","right":"Hard"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Slow","right":"Fast"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Forgettable","right":"Unforgettable"}'::jsonb, 'opinion', 2),
  ('dial', '{"left":"Casual","right":"Formal"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Guilty pleasure","right":"Proud of it"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Rude","right":"Polite"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Childish","right":"Grown-up"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Weird","right":"Normal"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Comfortable","right":"Painful"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Fragile","right":"Indestructible"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Ordinary","right":"Magical"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Fake","right":"Authentic"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Messy","right":"Tidy"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Dangerous","right":"Safe"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Cheesy","right":"Cool"}'::jsonb, 'opinion', 2),
  ('dial', '{"left":"Wholesome","right":"Sinister"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Relaxing","right":"Stressful"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Nobody likes it","right":"Everybody likes it"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Easy to learn","right":"Impossible to master"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Terrible advice","right":"Great advice"}'::jsonb, 'opinion', 2),
  ('dial', '{"left":"Waste of money","right":"Worth every penny"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Smells bad","right":"Smells great"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Dry","right":"Wet"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Dark","right":"Bright"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Bitter","right":"Sweet"}'::jsonb, 'food', 1),
  ('dial', '{"left":"Bland","right":"Spicy"}'::jsonb, 'food', 1),
  ('dial', '{"left":"Healthy","right":"Unhealthy"}'::jsonb, 'food', 1),
  ('dial', '{"left":"Snack","right":"Full meal"}'::jsonb, 'food', 1),
  ('dial', '{"left":"Breakfast food","right":"Dinner food"}'::jsonb, 'food', 2),
  ('dial', '{"left":"Best cold","right":"Best hot"}'::jsonb, 'food', 2),
  ('dial', '{"left":"Cheap night out","right":"Luxury night out"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Introvert activity","right":"Extrovert activity"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Do it alone","right":"Do it in a crowd"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Awkward","right":"Smooth"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Bad first date","right":"Great first date"}'::jsonb, 'social', 2),
  ('dial', '{"left":"White lie","right":"Serious betrayal"}'::jsonb, 'abstract', 3),
  ('dial', '{"left":"Forgivable","right":"Unforgivable"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Petty","right":"Justified"}'::jsonb, 'abstract', 3),
  ('dial', '{"left":"Luck","right":"Skill"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Talent","right":"Hard work"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"A want","right":"A need"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"A hobby","right":"A lifestyle"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Temporary","right":"Permanent"}'::jsonb, 'abstract', 1),
  ('dial', '{"left":"Overthinking it","right":"Not thinking at all"}'::jsonb, 'abstract', 3),
  ('dial', '{"left":"Superstition","right":"Science"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Common knowledge","right":"Obscure trivia"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Easy to fake","right":"Impossible to fake"}'::jsonb, 'abstract', 3),
  ('dial', '{"left":"Sounds fun","right":"Actually fun"}'::jsonb, 'abstract', 3),
  ('dial', '{"left":"Better in theory","right":"Better in practice"}'::jsonb, 'abstract', 3),
  ('dial', '{"left":"Fits in a pocket","right":"Needs a van"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Disposable","right":"Heirloom"}'::jsonb, 'everyday', 2),
  ('dial', '{"left":"Everyday item","right":"Once-a-year item"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Chore","right":"Treat"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Ten minutes","right":"All weekend"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Do it yourself","right":"Hire a professional"}'::jsonb, 'everyday', 2),
  ('dial', '{"left":"Morning person","right":"Night person"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Indoors","right":"Outdoors"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"City","right":"Countryside"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Old-fashioned","right":"Futuristic"}'::jsonb, 'everyday', 1),
  ('dial', '{"left":"Dying out","right":"Taking over"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Was better before","right":"Is better now"}'::jsonb, 'opinion', 2),
  ('dial', '{"left":"Hate to admit it","right":"Happy to shout it"}'::jsonb, 'social', 3),
  ('dial', '{"left":"Embarrassing","right":"Impressive"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Nobody notices","right":"Everybody notices"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Quietly annoying","right":"Instantly enraging"}'::jsonb, 'opinion', 2),
  ('dial', '{"left":"Minor inconvenience","right":"Ruins your day"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Mildly nice","right":"Life-changing"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Beginner","right":"Expert"}'::jsonb, 'abstract', 1),
  ('dial', '{"left":"Overthought","right":"Thrown together"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Ugly but works","right":"Beautiful but useless"}'::jsonb, 'opinion', 3),
  ('dial', '{"left":"Style","right":"Substance"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Cute","right":"Terrifying"}'::jsonb, 'opinion', 1),
  ('dial', '{"left":"Harmless","right":"Deadly"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"Sounds made up","right":"Obviously real"}'::jsonb, 'abstract', 2),
  ('dial', '{"left":"Villain","right":"Hero"}'::jsonb, 'abstract', 1),
  ('dial', '{"left":"Follows the rules","right":"Breaks the rules"}'::jsonb, 'social', 1),
  ('dial', '{"left":"Would tell a stranger","right":"Would tell nobody"}'::jsonb, 'social', 3),
  ('dial', '{"left":"Fine to be late for","right":"Never be late for"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Acceptable gift","right":"Insulting gift"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Text about it","right":"Call about it"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Split the bill","right":"One person pays"}'::jsonb, 'social', 2),
  ('dial', '{"left":"Fine to eat with hands","right":"Cutlery only"}'::jsonb, 'food', 2),
  ('dial', '{"left":"Kids love it","right":"Adults love it"}'::jsonb, 'food', 2),
  ('dial', '{"left":"Better homemade","right":"Better shop-bought"}'::jsonb, 'food', 2),
  ('dial', '{"left":"One is enough","right":"Can''t stop at one"}'::jsonb, 'food', 2),
  ('dial', '{"left":"Comfort food","right":"Fancy food"}'::jsonb, 'food', 1),
  ('dial', '{"left":"Smooth","right":"Crunchy"}'::jsonb, 'food', 1),
  ('dial', '{"left":"A drizzle","right":"A downpour"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"A tap","right":"A punch"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"A whisper","right":"A scream"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"A puddle","right":"An ocean"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"A hill","right":"A mountain"}'::jsonb, 'physical', 1),
  ('dial', '{"left":"A hobby project","right":"A world record attempt"}'::jsonb, 'abstract', 3),
  ('season', '{"text":"Red beats black, whatever the number."}'::jsonb, 'suit', 1),
  ('season', '{"text":"Black beats red, whatever the number."}'::jsonb, 'suit', 1),
  ('season', '{"text":"Lowest card wins the trick."}'::jsonb, 'order', 1),
  ('season', '{"text":"Nobody may play a face card."}'::jsonb, 'hand', 1),
  ('season', '{"text":"The winner of a trick leads the next one with their eyes closed."}'::jsonb, 'ritual', 2),
  ('season', '{"text":"Whoever wins a trick gives one card from their hand to the player on their left."}'::jsonb, 'hand', 2),
  ('season', '{"text":"If you hold the led suit you must play your highest one."}'::jsonb, 'order', 2),
  ('season', '{"text":"Following suit is off. Play anything you like."}'::jsonb, 'order', 1),
  ('season', '{"text":"Aces are the lowest card in the deck."}'::jsonb, 'order', 1),
  ('season', '{"text":"The second card played wins the trick."}'::jsonb, 'order', 2),
  ('season', '{"text":"Hearts cannot win a trick, ever."}'::jsonb, 'suit', 1),
  ('season', '{"text":"Everyone plays face down. Flip together once all cards are in."}'::jsonb, 'ritual', 2),
  ('season', '{"text":"Whoever wins a trick sits the next one out."}'::jsonb, 'ritual', 2),
  ('season', '{"text":"Everyone plays with their hand face up on the table."}'::jsonb, 'hand', 2),
  ('season', '{"text":"No talking. Not one word, all season."}'::jsonb, 'silence', 1),
  ('season', '{"text":"The trick goes to whoever played closest to seven."}'::jsonb, 'order', 2),
  ('season', '{"text":"The winner of a trick must lead the same suit again."}'::jsonb, 'order', 2),
  ('season', '{"text":"Every player must play their leftmost card."}'::jsonb, 'hand', 1),
  ('season', '{"text":"Even numbers beat odd numbers. Faces are odd."}'::jsonb, 'order', 2),
  ('season', '{"text":"The leader names a suit out loud. Nobody may play it."}'::jsonb, 'suit', 2),
  ('season', '{"text":"Clubs beat everything."}'::jsonb, 'suit', 1),
  ('season', '{"text":"Play one-handed, and not the hand you write with."}'::jsonb, 'ritual', 1),
  ('season', '{"text":"The trick goes to the second-lowest card played."}'::jsonb, 'order', 3),
  ('season', '{"text":"Nobody may play the same suit as the card before it."}'::jsonb, 'suit', 3),
  ('season', '{"text":"Announce your card out loud before you play it. Lying is allowed."}'::jsonb, 'silence', 2),
  ('season', '{"text":"The winner of a trick plays the next one blind — card face down, unseen."}'::jsonb, 'ritual', 2),
  ('season', '{"text":"Twos beat aces. Everything else is normal."}'::jsonb, 'order', 1),
  ('season', '{"text":"Nobody may win two tricks running. If you would, it goes to the player on your left."}'::jsonb, 'order', 3),
  ('season', '{"text":"Before each trick, everyone buries one card in the middle. It counts for nobody."}'::jsonb, 'hand', 2),
  ('season', '{"text":"Whoever played the lowest card leads the next trick."}'::jsonb, 'order', 1),
  ('season', '{"text":"You may look at the tricks the player on your right has taken before you play."}'::jsonb, 'ritual', 1),
  ('season', '{"text":"Diamonds are worthless. A trick won entirely in diamonds goes to nobody."}'::jsonb, 'suit', 3),
  ('season', '{"text":"Play with your cards held backwards, faces out to the table."}'::jsonb, 'hand', 3),
  ('season', '{"text":"The player who wins a trick must swap one card with the player across from them."}'::jsonb, 'hand', 2),
  ('envelope', '{"text":"End the game holding more black cards than red.","points":3}'::jsonb, 'count', 1),
  ('envelope', '{"text":"End the game holding more red cards than black.","points":3}'::jsonb, 'count', 1),
  ('envelope', '{"text":"Make sure {right} ends the game holding an ace.","points":4}'::jsonb, 'other', 1),
  ('envelope', '{"text":"Hold exactly seven cards at the end. No more, no less.","points":4}'::jsonb, 'count', 1),
  ('envelope', '{"text":"End the game holding no face cards at all.","points":3}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding all four of one number.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Hold more cards than anyone else at the table.","points":4}'::jsonb, 'count', 1),
  ('envelope', '{"text":"Hold fewer cards than anyone else at the table.","points":4}'::jsonb, 'count', 1),
  ('envelope', '{"text":"End the game holding at least three hearts.","points":3}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Make sure {left} ends the game with no hearts at all.","points":5}'::jsonb, 'other', 1),
  ('envelope', '{"text":"End the game holding three in a row of one suit.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Trade away every club you are dealt. End with none.","points":3}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding both black queens.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Give {right} at least four cards over the whole game.","points":4}'::jsonb, 'other', 1),
  ('envelope', '{"text":"Take at least three cards from {left} over the whole game.","points":4}'::jsonb, 'other', 1),
  ('envelope', '{"text":"End the game holding exactly one of the cards you were dealt.","points":4}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding cards adding up to more than fifty.","points":4}'::jsonb, 'count', 1),
  ('envelope', '{"text":"End the game holding cards adding up to less than fifteen.","points":4}'::jsonb, 'count', 1),
  ('envelope', '{"text":"Hold exactly three cards at the end.","points":5}'::jsonb, 'count', 1),
  ('envelope', '{"text":"Make sure {right} ends with more cards than {left}.","points":5}'::jsonb, 'other', 1),
  ('envelope', '{"text":"End the game holding at least one card of every suit.","points":3}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding nothing but a single suit.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Own the king of hearts at the end.","points":4}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding an even number of cards.","points":2}'::jsonb, 'count', 1),
  ('envelope', '{"text":"End the game holding a card you took from {right}.","points":3}'::jsonb, 'other', 1),
  ('envelope', '{"text":"Trade at least once with every single player.","points":3}'::jsonb, 'social', 1),
  ('envelope', '{"text":"Never refuse a trade that is offered to you.","points":4}'::jsonb, 'social', 1),
  ('envelope', '{"text":"Refuse the first three trades you are offered.","points":4}'::jsonb, 'social', 1),
  ('envelope', '{"text":"End the game holding two cards of the same number.","points":3}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Make sure {left} ends the game holding a two.","points":4}'::jsonb, 'other', 1),
  ('envelope', '{"text":"End the game holding the highest single card at the table.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding nothing above an eight.","points":4}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Say the word \"lovely\" in every session without anyone calling you on it.","points":3}'::jsonb, 'social', 1),
  ('envelope', '{"text":"End the game holding more cards than you were dealt.","points":3}'::jsonb, 'count', 1),
  ('envelope', '{"text":"Give away every card you were dealt. Keep none of them.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Talk someone into giving you a card for nothing, twice.","points":4}'::jsonb, 'social', 1),
  ('envelope', '{"text":"End the game holding exactly as many cards as you started with.","points":2}'::jsonb, 'count', 1),
  ('envelope', '{"text":"Make sure {right} never receives a single card from you.","points":3}'::jsonb, 'other', 1),
  ('envelope', '{"text":"End the game holding at least two aces.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding a three of any suit.","points":2}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"End the game holding a jack, a queen and a king.","points":5}'::jsonb, 'shape', 1),
  ('envelope', '{"text":"Make sure the player holding the most cards is not you and not {left}.","points":4}'::jsonb, 'other', 1)
) as v(game_type, payload, category, difficulty)
where not exists (
  select 1 from content_items c
  where c.game_type = v.game_type and c.payload = v.payload
);
